### ISSUE TITLE
GSOC 2023 Proposal

### ISSUE THREAD

**Issue by AggelosMargkas** [dspinellis/alexandria3k#3]
Greeting Mr Diomidis,

I have uploaded my proposal for the GSOC 2023 with regards to the addition of extensions in Alexandria3k. I would love to hear back feedback from you, so to make it better and maybe clarify some parts.

Kind Regards,
Aggelos Margkas.

**Comment by dspinellis** [comment]
Thank you for your interest.  I will review it and get back to you.  Please use GitHub issues only for posting bugs or requests for concrete features of Alexandria3k.
